/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class YcsbLevelDB */

#ifndef _Included_YcsbLevelDB
#define _Included_YcsbLevelDB
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     YcsbLevelDB
 * Method:    nativeInit
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_YcsbLevelDB_nativeInit
  (JNIEnv *, jobject);

/*
 * Class:     YcsbLevelDB
 * Method:    nativeRead
 * Signature: (Ljava/lang/String;Ljava/lang/String;Ljava/lang/StringBuilder;)I
 */
JNIEXPORT jint JNICALL Java_YcsbLevelDB_nativeRead
  (JNIEnv *, jobject, jstring, jstring, jobject);

/*
 * Class:     YcsbLevelDB
 * Method:    nativeScan
 * Signature: (Ljava/lang/String;Ljava/lang/String;ILjava/util/Vector;)I
 */
JNIEXPORT jint JNICALL Java_YcsbLevelDB_nativeScan
  (JNIEnv *, jobject, jstring, jstring, jint, jobject);

/*
 * Class:     YcsbLevelDB
 * Method:    nativeInsert
 * Signature: (Ljava/lang/String;Ljava/lang/String;Ljava/lang/String;)I
 */
JNIEXPORT jint JNICALL Java_YcsbLevelDB_nativeInsert
  (JNIEnv *, jobject, jstring, jstring, jstring);

/*
 * Class:     YcsbLevelDB
 * Method:    nativeDelete
 * Signature: (Ljava/lang/String;Ljava/lang/String;)I
 */
JNIEXPORT jint JNICALL Java_YcsbLevelDB_nativeDelete
  (JNIEnv *, jobject, jstring, jstring);

#ifdef __cplusplus
}
#endif
#endif
