/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_yahoo_ycsb_YcsbLevelDB */

#ifndef _Included_com_yahoo_ycsb_YcsbLevelDB
#define _Included_com_yahoo_ycsb_YcsbLevelDB
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_yahoo_ycsb_YcsbLevelDB
 * Method:    nativeInit
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_com_yahoo_ycsb_YcsbLevelDB_nativeInit
  (JNIEnv *, jobject);

/*
 * Class:     com_yahoo_ycsb_YcsbLevelDB
 * Method:    nativeRead
 * Signature: (Ljava/lang/String;Ljava/lang/String;Ljava/util/Set;Ljava/util/HashMap;)I
 */
JNIEXPORT jint JNICALL Java_com_yahoo_ycsb_YcsbLevelDB_nativeRead
  (JNIEnv *, jobject, jstring, jstring, jobject, jobject);

/*
 * Class:     com_yahoo_ycsb_YcsbLevelDB
 * Method:    nativeScan
 * Signature: (Ljava/lang/String;Ljava/lang/String;ILjava/util/Set;Ljava/util/Vector;)I
 */
JNIEXPORT jint JNICALL Java_com_yahoo_ycsb_YcsbLevelDB_nativeScan
  (JNIEnv *, jobject, jstring, jstring, jint, jobject, jobject);

/*
 * Class:     com_yahoo_ycsb_YcsbLevelDB
 * Method:    nativeInsert
 * Signature: (Ljava/lang/String;Ljava/lang/String;Ljava/util/HashMap;)I
 */
JNIEXPORT jint JNICALL Java_com_yahoo_ycsb_YcsbLevelDB_nativeInsert
  (JNIEnv *, jobject, jstring, jstring, jobject);

/*
 * Class:     com_yahoo_ycsb_YcsbLevelDB
 * Method:    nativeDelete
 * Signature: (Ljava/lang/String;Ljava/lang/String;)I
 */
JNIEXPORT jint JNICALL Java_com_yahoo_ycsb_YcsbLevelDB_nativeDelete
  (JNIEnv *, jobject, jstring, jstring);

/*
 * Class:     com_yahoo_ycsb_YcsbLevelDB
 * Method:    nativeUpdate
 * Signature: (Ljava/lang/String;Ljava/lang/String;Ljava/util/HashMap;)I
 */
JNIEXPORT jint JNICALL Java_com_yahoo_ycsb_YcsbLevelDB_nativeUpdate
  (JNIEnv *, jobject, jstring, jstring, jobject);

#ifdef __cplusplus
}
#endif
#endif
